[versions]
flyway = "12.0.1"
jooq = "3.20.11"
junit = "6.0.3"
kotlin = "2.3.10"
plantuml = "1.2026.1"
postgresql = "42.7.10"
structurizr = "6.0.0"

[libraries]
flyway-core = { group = "org.flywaydb", name = "flyway-core", version.ref = "flyway" }
flyway-postgresql = { group = "org.flywaydb", name = "flyway-database-postgresql", version.ref = "flyway" }
jooq = { group = "org.jooq", name = "jooq", version.ref = "jooq" }
jooq-meta = { group = "org.jooq", name = "jooq-meta", version.ref = "jooq" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter-api = { group = "org.junit.jupiter", name = "junit-jupiter-api" }
junit-jupiter-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine" }
junit-platform-launcher = { group = "org.junit.platform", name = "junit-platform-launcher" }
plantuml = { group = "net.sourceforge.plantuml", name = "plantuml", version.ref = "plantuml" }
postgresql = { group = "org.postgresql", name = "postgresql", version.ref = "postgresql" }
structurizr-autolayout = { group = "com.structurizr", name = "structurizr-autolayout", version.ref = "structurizr" }
structurizr-client = { group = "com.structurizr", name = "structurizr-client", version.ref = "structurizr" }
structurizr-export = { group = "com.structurizr", name = "structurizr-export", version.ref = "structurizr" }

[plugins]
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
versionCatalogLinter = { id = "io.github.pemistahl.version-catalog-linter", version = "1.1.0" }
