services:
    devcontainer:
        image: mcr.microsoft.com/devcontainers/base:ubuntu@sha256:3dcb059253b2ebb44de3936620e1cff3dadcd2c1c982d579081ca8128c1eb319
        volumes:
            - ..:/workspaces/kokus-recipe-app:cached
        command: sleep infinity
        depends_on:
            - db
